### ISSUE TITLE
Collections with name started by 'system' was not cleaned

### ISSUE THREAD

**Issue by loyl** [lordofthejars/nosql-unit#125]
I create a collection "systemBlacklistRecipients" and this collection was not cleaned by CLEAN_INSERT strategy because the name starts with "system" : 

```java
private boolean isNotASystemCollection(String collectionName) {
	return !collectionName.startsWith("system");
}
```

The MongoDB doc say :
> The .system.* namespaces in MongoDB are special and contain database system information. 

I think the correct implementation of isNotASystemCollection method must be :

```java
private boolean isNotASystemCollection(String collectionName) {
	return !collectionName.startsWith("system.");
}
```

**Comment by lordofthejars** [comment]
Thank you so much for your feedback, yes I will implement as you mention to avoid this problem
