### ISSUE TITLE
MongoDb: UsingDataSet with ObjectID.

### ISSUE THREAD

**Issue by littlebaka** [lordofthejars/nosql-unit#129]
Hi,
I would like to know if there is way to use ObjectID as id (insted of String).

transform (in dataset)
```json
"data":[
  {
    "_id" : "54f6ded6de7314ad835e2dad",
  }
```
into (in mongodb) 
```json
   "_id" : ObjectID("54f6ded6de7314ad835e2dad")
```

actually (in mongodb) 
```json
   "_id" : "54f6ded6de7314ad835e2dad"
```

Edit: It's possible to implement an auto ObjectId detection/converter? Something like that:

```java

if(ObjectId.isValid(myString))
  return new ObjectID(myString);

```

**Comment by victorhernandezbermejo** [comment]
Defining the data with `$oid` as should do the work:


    "data":[
      {
           "_id" : { "$oid" : "54f6ded6de7314ad835e2dad" },
      }

**Comment by littlebaka** [comment]
Thank you very much, it works fine.
