### ISSUE TITLE
Populate two MongoDB dbs at one unit test

### ISSUE THREAD

**Issue by morm** [lordofthejars/nosql-unit#131]
Hi. Is it possible to set collection's data in two dbs with one UsingDataSet? Or is there another way to populate two dbs for one unit test?

**Comment by lordofthejars** [comment]
Hi, I think that what you are looking for is this https://github.com/lordofthejars/nosql-unit#simultaneous-engines

**Comment by morm** [comment]
Yes, thank you. That's just what I needed. Thanx for great tool too ))

**Comment by lordofthejars** [comment]
Thank you so much for using nosqlunit :)
