### ISSUE TITLE
support YAML data for MongoDB

### ISSUE THREAD

**Issue by chrylis** [lordofthejars/nosql-unit#134]
YAML is a lot more concise than JSON for representing a number of documents. What would it take to support YAML as an alternative data source (for load, if not necessarily for output comparison)?

**Comment by lordofthejars** [comment]
Hi in fact you can implement it by using https://github.com/lordofthejars/nosql-unit#customizing-insertion-and-comparation-strategy If you implement and wants to share it you can send me PR and we will incorporate this file format as supported one.

Thank you so much for using NoSQLUnit.
