### ISSUE TITLE
How to use ISODate in dataset(MongoDB)

### ISSUE THREAD

**Issue by hacking2** [lordofthejars/nosql-unit#147]
Hi, I am using nosql-unit-mongodb, fongo, and have some problem.

when using @ShouldMatchDataSet or @UsingDataSet, I wrote like below

//expected.json
```javascript
  {
      "people" : {
          "data" : [
              {
                  "key" : "12345",
                  "phone" : "33333",
                  "register" : "2011-01-05T10:09:15.210Z", //It is ISODate, How can I convert Joda DateTime?
                  "index" : 1
              }
          ]
      }
  }
```

my domain object like this

```java
  @Id
  private ObjectId id;

  @Field("key")
  private String key;

  @Field("phone")
  private String phone;

  @Indexed(unique=true, direction=IndexDirection.DESCENDING)
  @Field("index")
  private long index;

  @Field("register")
  private DateTime register;
```

when I load data, register always null. How can I write ISODate format in expected file?

Thanks for your help

**Comment by lordofthejars** [comment]
Does inside MongoDB stored correctly as ISODate? Notice that from the point of view of NoSQLUnit we are using the MongoDB util class `DBObject parsedData = (DBObject) JSON.parse(jsonData)` so probably the data is correctly inserted into MongoDB, the problem you might find probably is related with mapper library used.

**Comment by joergreichert** [comment]
the following works for me (using java.util.Date instead of DateTime)
`
  {
      "people" : {
          "data" : [
              {
                  "key" : "12345",
                  "phone" : "33333",
                  "register" : {
		     "$date": "2011-01-05T10:09:15.210Z"
                  },
                  "index" : 1
              }
          ]
      }
  }
`

**Comment by choda** [comment]
I can confirm the _$date_ notation also works Joda DateTime objects.

It is actually the representation of _data_date_ objects the [MongoDB Extended JSON](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#mongodb-extended-json) strict mode.

Representation of datetime and other BSON data types (object ids, db refs...) in JSON strict mode is given on the [MongoDB reference manual](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#bson-data-types-and-associated-representations).

**Comment by choda** [comment]
Btw, the question was also asked and answered [here](https://github.com/fakemongo/fongo/issues/13), and [here](https://github.com/fakemongo/fongo/issues/173) (by the same poster).
