### ISSUE TITLE
Is there javadoc anywhere? 

### ISSUE THREAD

**Issue by dwjohnston** [lordofthejars/nosql-unit#157]
I'm needing to explore the code a bit to understand what's happening with these annotations and class rules and such, and Javadoc would be the easiest way to the see the types etc. 

Is the javadoc online somewhere?

**Comment by lordofthejars** [comment]
Saldy not :(

**Comment by joschi** [comment]
@dwjohnston You can access the Javadoc of this project via javadoc.io, e. g. https://javadoc.io/doc/com.lordofthejars/nosqlunit-core/0.10.0 or https://javadoc.io/doc/com.lordofthejars/nosqlunit-mongodb/0.10.0

**Comment by lordofthejars** [comment]
Thank you so much.
