### ISSUE TITLE
@UsingDataSet doesn't let me specify resources: 

### ISSUE THREAD

**Issue by dwjohnston** [lordofthejars/nosql-unit#158]
I would like to have a folder in `src/test/resources` where I list a few different types of graphs, and choose which one to use at the top of each test. 

eg: 

	@RunWith(SpringJUnit4ClassRunner.class)
	@ContextConfiguration(locations = { "classpath:config/spring/graph-test-context.xml" })
	@UsingDataSet(locations = "classpath:graphml/graph1.xml", loadStrategy = LoadStrategyEnum.CLEAN_INSERT)
	public class GraphTest {

The problem I have, is that this will give me the error: 

java.lang.IllegalArgumentException: File specified in locations property are not present in classpath, or no files matching default name are found. Valid default locations are: /com/my/package/GraphTest.xml or /com/my/package/GraphTest#addNode_allowDupesEqYes_addsNodeWithDupes.xml

Here's my proof that the resources are indeed being added to the classpath: 

	@Before
	public void test() throws IOException {
		
		System.out.println("--");
		ClassLoader cl = this.getClass().getClassLoader(); 
		ResourcePatternResolver resolver = new PathMatchingResourcePatternResolver(cl);
		Resource[] resources = resolver.getResources("classpath:graphml/*.xml") ;
		for (Resource resource: resources){
		    System.out.println(resource.getFilename());
		}
		

	}

returns: 

    graph1.xml
    GraphTest.xml
    TestTest.xml

Have I got something configured wrong, or has `@UsingDataSet` got a bug?

**Comment by lordofthejars** [comment]
Hi I think that that what you are doing wrong is using Spring syntax in `@UsingDataSet`. By default datasets must be in the classpath so you don't have to do:  `@UsingDataSet(locations = "classpath:graphml/graph1.xml",....` but `@UsingDataSet(locations = "graphml/graph1.xml",`

**Comment by scne** [comment]
Up

**Comment by choda** [comment]
Add a leading slash (you can also get rid of the curly brackets when there is only one dataset:
```
@Test
    @UsingDataSet(locations = "/dataset.json", loadStrategy= LoadStrategyEnum.CLEAN_INSERT)
    public void readAndupdateTemplate(){

        ...

    }
```

**Comment by lordofthejars** [comment]
Thanks for the answer @choda
