### ISSUE TITLE
ClassCastException in Group at Util.extractField

### ISSUE THREAD

**Issue by joergreichert** [lordofthejars/nosql-unit#161]
With calling aggregate and using group by sum for float field "my_attribute"

`mongoTemplate.aggregate(agg,` "my_collection", `Map.class);`

this causes a ClassCastException at line with Util.extractField (String cannot be cast to number)

`com.github.fakemongo.impl.aggregation.Group.sum(DBCollection, Object)`

```
Number result= null;
...
// object = { "my_attribute" : "123.45"}  
// field = "my_attribute"
result = Util.extractField(object, field); // com.github.fakemongo.impl.Util.extractField(DBObject, String)
```

Inside "object" the value is actual a string. 

But using an explicit class instead, e.g. a custom class Result, having myAttribute with the correct type doesn't help: object still contains a string as value.

So either the code should try to parse the String as Number (instead of casting it) or assure that the value is of correct type.

**Comment by lordofthejars** [comment]
Can you paste the whole stack trace? It seems a problem with fakemongo rather than nosqlunit ?

**Comment by joergreichert** [comment]
Yes, you're right. I wasn't aware that nosqlunit and fongo are different projects. I created a new bug for fongo: https://github.com/fakemongo/fongo/issues/224

**Comment by lordofthejars** [comment]
Thank you very much for using nosqlunit

**Comment by joergreichert** [comment]
For your interest: https://github.com/fakemongo/fongo/issues/224#issuecomment-241468965

Bit I'm not sure, on which side the bug should be fixed.
