### ISSUE TITLE
Using @UsingDataSet at Class level

### ISSUE THREAD

**Issue by pvpkiran** [lordofthejars/nosql-unit#162]
Hi,
  I have a lot of test cases in my Test class. All of it needs the same data to be in Mongo. And hence I use @UsingDataSet for each test case. 
My question is, whether I can use @UsingDataSet once for the whole class and all the test cases in my test class can use it. 
Be definition @UsingDataSet annotation cannot be used at class level. but is there an alternative instead of using @UsingDataSet multiple times in the same class.?

Thanks

**Comment by lordofthejars** [comment]
Hi, first of all thank you very much for using NoSQLUnit. You can use `@UsingDataSet` at class level if you want (https://github.com/lordofthejars/nosql-unit/blob/master/nosqlunit-core/src/main/java/com/lordofthejars/nosqlunit/annotation/UsingDataSet.java#L11)

**Comment by pvpkiran** [comment]
Sorry, I overlooked it.
