### ISSUE TITLE
Use nosql-unit with couchbase DB

### ISSUE THREAD

**Issue by wadel86** [lordofthejars/nosql-unit#166]
Hi,

nosql-unit can be used to insert data in couchbase DB ?

**Comment by lordofthejars** [comment]
Yes, there is a test https://github.com/lordofthejars/nosql-unit/tree/master/nosqlunit-demo/src/test/java/com/lordofthejars/nosqlunit/demo/couchbase

**Comment by wadel86** [comment]
Thank you very much for the reply, Sorry I didn't saw the demo.
