### ISSUE TITLE
Redis select DB

### ISSUE THREAD

**Issue by krupet** [lordofthejars/nosql-unit#173]
Good day!
Did I understand right from [dataset reader](https://github.com/lordofthejars/nosql-unit/blob/master/nosqlunit-redis/src/main/java/com/lordofthejars/nosqlunit/redis/parser/DataReader.java#L18)  that nosqlunit-redis do not support selection databases yet?
For instance, in our project most of the collections are stored in DB0 and some are segregated into DB1.

**Comment by lordofthejars** [comment]
No, it is not supported yet, but it should be easy to implement, not as dataset but as connection option, like happens with MongoDB https://github.com/lordofthejars/nosql-unit#configuring-mongodb-connection Or it has not sense at all?

**Comment by krupet** [comment]
Many thanks!
By the way, thanks for a great project!

**Comment by lordofthejars** [comment]
Thank you to use it, if you want feel free to provide a PR adding this new feature
