### ISSUE TITLE
Can't retrieve info with Spring Data from Fongoed MongoDB

### ISSUE THREAD

**Issue by Pavel-Soloduha** [lordofthejars/nosql-unit#177]
Greeting. 
I am using:
- Spring boot 1.5.9
- Fongo 2.1.0
- nosql-unit 0.14.0
- JUnit 4.12

And after some tests I stuck with following results.
Configuration:
```
public class FongoConfiguration extends AbstractMongoConfiguration {

    public static final String DATABASE_NAME = "test-db";

    @Override
    protected String getDatabaseName() {
        return DATABASE_NAME;
    }

    @Bean
    @Override
    public Mongo mongo() {
        System.out.println("I alive");
        return new Fongo(getDatabaseName()).getMongo();
    }

    @Bean
    public MongoTemplate mongoTemplate() {
        return new MongoTemplate(mongo(), DATABASE_NAME);
    }

}
```

And tests for Fongo with nosql-unit.
```
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {AppStarter.class})
public class GroupRepositorySpringDataTest {

    @Rule
    public MongoDbRule mongoDbRule = newMongoDbRule().defaultSpringMongoDb(FongoConfiguration.DATABASE_NAME);

    @Autowired
    private ApplicationContext applicationContext;

    @Autowired
    private GroupRepository groupRepository;

    @Test
    @UsingDataSet(locations = {"/Group.json"}, loadStrategy = LoadStrategyEnum.CLEAN_INSERT)
    public void test() {
        System.out.println(groupRepository.findAll());
    }
}
```
In this scenario 
`@UsingDataSet(locations = {"/Group.json"}, loadStrategy = LoadStrategyEnum.CLEAN_INSERT)` work as it intended and set data to "test-db", but repository can't get it.

As for embedded scenario in logs I see that bean with Fongo is created, but still no return from repository. 
```
    @ClassRule
    public static InMemoryMongoDb inMemoryMongoDb = newInMemoryMongoDbRule().build();

    @Rule
    public MongoDbRule mongoDbRule = newMongoDbRule().defaultEmbeddedMongoDb(FongoConfiguration.DATABASE_NAME);

```

I will be grateful if you show me way to solve it.

**Comment by lordofthejars** [comment]
Look here you an find an example: https://arthurportas.wordpress.com/2017/01/21/sample-project-using-spring-boot-and-mongodbfongo-and-test-repository-with-nosqlunit/

**Comment by Pavel-Soloduha** [comment]
So, I reviewed my code again, and solve 2 problems but find another one.
So for  
```
@Rule
public MongoDbRule mongoDbRule = newMongoDbRule().defaultSpringMongoDb(FongoConfiguration.DATABASE_NAME);
```
It was my bad, cause in Spring context was declared another database, and Fongo is working too as well.

But now somehow data from 
`    @UsingDataSet(locations = {"/Group.json"}, loadStrategy = LoadStrategyEnum.CLEAN_INSERT)`
doesn't appear in DB, but in logs I can see that data is inserted. And if I manually insert data everything looks fine.
```
System.out.println(groupRepository.findAll());//[]
DBCollection collection = mongoTemplate.getCollection("Group");
collection.insert(new BasicDBObject("title", "Life"));
System.out.println(collection.find().count());//1
System.out.println(groupRepository.findAll());//inserted data
```
Logs:
```
@UsingDataSet
com.mongodb.FongoDBCollection            : insert: { "title" : "Books"}
com.mongodb.FongoDBCollection            : applying projections { "_id" : 1}
com.mongodb.FongoDBCollection            : applying projections { "_id" : 1}
com.mongodb.FongoDBCollection            : applying projections { "_id" : 1}
```
```
Manual insertion
com.mongodb.FongoDBCollection            : insert: { "title" : "Life"}
com.mongodb.FongoDBCollection            : applying projections { "_id" : 1}
com.mongodb.FongoDBCollection            : applying projections { "_id" : 1}
com.mongodb.FongoDBCollection            : applying projections { "_id" : 1}
```

**Comment by Pavel-Soloduha** [comment]
After several tests I got error as here. 
[https://stackoverflow.com/questions/29620819/nosqlunit-mongodb-insert-collection-names-are](url)

So for now nosql-unit will be used for init of fongo and insert data in real mongo.

Thanks for your help.

**Comment by Pavel-Soloduha** [comment]
So it's me again. I found and solve problem, and it was me, cause I removed these annotations from config class. Thanks for great tool.
```
@Configuration
@EnableMongoRepositories
```
