### ISSUE TITLE
Connection refused to embeded Redis with Spring-data

### ISSUE THREAD

**Issue by nicolasguyomar** [lordofthejars/nosql-unit#95]
Hi, 

I'm trying to use both Embeded Redis with Spring-data in JUnit test, but fail to connect to the started Redis instance.

Everything works fine if I use the embeded Redis with an injected Jedis instance :

```
    @Rule
public RedisRule redisRule = newRedisRule().defaultEmbeddedRedis();

    @ClassRule
public static EmbeddedRedis embeddedRedis = newEmbeddedRedisRule().build();

@Inject
public Jedis jedis;

@Test
public void simpleGet() {
    String name = jedis.get("key1");
    assertThat(name, is("value1"));
}
```

But as soon as I try to use a RedisTemplate instance, the connection gets refused : 

@Autowired
private RedisTemplate<String, Object> redisTemplate;

Here is my spring application-context.xml (which is well loaded at start up)

```
    <!-- Activate annotation configured components -->
<context:annotation-config />
<context:component-scan base-package="com.thalesgroup.stif.ordonnanceur.persistence" />

<!-- redis template definition -->
<bean id="redisTemplate" class="org.springframework.data.redis.core.RedisTemplate"
    p:connection-factory-ref="jedisConnectionFactory" />

<!-- Jedis ConnectionFactory -->
<bean id="jedisConnectionFactory"
    class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory" 
    p:hostName="localhost" p:port="6379" p:usePool="false" />
```

If I insert a breakpoint during my test, I can't see any process using the 6379 port, even if the doStart of the EmbeddedRedisLifecycleManager class succeed.

Does someone know which hostname I should use to connect to the embeded redis instance ?

Thanks

**Comment by ashanelluri** [comment]
how to inject embedded server information into jedis connectioin factory?

**Comment by lordofthejars** [comment]
You cannot since it is an embeded instance
